# Files

PATH = './data/'
FOUR_CLUSTERS = PATH + '4clusters.csv'
ACCIDENTS_1 = PATH + 'AccidentsSet01.csv'
ACCIDENTS_2 = PATH + 'AccidentsSet02.csv'
ACCIDENTS_3 = PATH + 'AccidentsSet03.csv'
BIRTH_DEATH_RATE = PATH + 'birth_death_rate.csv'
ECONOMY = PATH + 'economy.csv'
MAMMALS = PATH + 'mammal_milk.csv'
MANY_CLUSTERS = PATH + 'many_clusters.csv'
PLANETS = PATH + 'planets.csv'
IRIS = PATH + 'iris.csv'

TWO_DIM = [FOUR_CLUSTERS, MANY_CLUSTERS, BIRTH_DEATH_RATE]

ALL = [MAMMALS, IRIS, MANY_CLUSTERS, PLANETS, ACCIDENTS_1, ACCIDENTS_2, ACCIDENTS_3, FOUR_CLUSTERS, BIRTH_DEATH_RATE,
       ECONOMY]

ks = {FOUR_CLUSTERS: 4, ACCIDENTS_1: 3, ACCIDENTS_2: 4, ACCIDENTS_3: 4, BIRTH_DEATH_RATE: 3, ECONOMY: 3, MAMMALS: 3,
      MANY_CLUSTERS: 7, PLANETS: 3, IRIS: 3}

e_pts = {FOUR_CLUSTERS: (12, 3), BIRTH_DEATH_RATE: (3, 2), ECONOMY: (12, 3), MAMMALS: (10, 2), MANY_CLUSTERS: (12, 3),
         PLANETS: (26, 5), ACCIDENTS_1: (4, 3), ACCIDENTS_2: (6, 3), IRIS: (0.9, 13), ACCIDENTS_3: (30, 3)}

DB_TESTS = [MAMMALS, IRIS, MANY_CLUSTERS, PLANETS, ACCIDENTS_1, ACCIDENTS_2, FOUR_CLUSTERS, BIRTH_DEATH_RATE,
            ECONOMY]


KMEANS_CENTROID_THRESHOLD = 1
KMEANS_SSE_THRESHOLD = 0.05
TOTALS = 'totals'
