# Files

PATH = './data/'
FOUR_CLUSTERS = PATH + '4clusters.csv'
ACCIDENTS_1 = PATH + 'AccidentsSet01.csv'
ACCIDENTS_2 = PATH + 'AccidentsSet02.csv'
ACCIDENTS_3 = PATH + 'AccidentsSet03.csv'
BIRTH_DEATH_RATE = PATH + 'birth_death_rate.csv'
ECONOMY = PATH + 'economy.csv'
MAMMALS = PATH + 'mammal_milk.csv'
MANY_CLUSTERS = PATH + 'many_clusters.csv'
PLANETS = PATH + 'planets.csv'
IRIS = PATH + 'iris.csv'

TWO_DIM = [FOUR_CLUSTERS, MANY_CLUSTERS, BIRTH_DEATH_RATE]
ALL = [ACCIDENTS_1, IRIS, FOUR_CLUSTERS, ACCIDENTS_2, ACCIDENTS_3, BIRTH_DEATH_RATE, ECONOMY, MAMMALS, MANY_CLUSTERS,
       PLANETS]

ks = {FOUR_CLUSTERS: 4, ACCIDENTS_1: 3, ACCIDENTS_2: 4, ACCIDENTS_3: 4, BIRTH_DEATH_RATE: 3, ECONOMY: 4, MAMMALS: 3,
      MANY_CLUSTERS: 7, PLANETS: 3, IRIS: 3}
